
export ZSH=$HOME/.oh-my-zsh

################ theme
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

################ custom config
# so as not the show the hostname
DEFAULT_USER=$USER
# POMPT='myPrompt'

################ plugins
# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

plugins=(git cargo sbt docker)

if [ $commands[kubectl] ]; then
function rprompt() {
  kubectl config current-context
}
fi

## color chart: https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg
# RPROMPT='$FG[246] $(rprompt)%{$reset_color%'


source $ZSH/oh-my-zsh.sh

# Include Common
if [ -f ~/.commonrc ]; then
  . ~/.commonrc
fi

################ user config
## Highlighting
# brew install zsh-syntax-highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


## Auto Complete
if [ $commands[aws] ]; then
  source /usr/local/share/zsh/site-functions/_aws
fi

## Brew
export HOMEBREW_NO_ANALYTICS=1

# Kube (slow!!)
# if [ $commands[kubectl] ]; then
#   source <(kubectl completion zsh)
# fi

# Helm
#if [ $commands[helm] ]; then
#  source <(helm completion zsh)
#fi


