
export ZSH=$HOME/.oh-my-zsh

################ theme
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="robbyrussell"
# ZSH_THEME="minimal_improve"
ZSH_THEME="avit"

################ custom config
# so as not the show the hostname
DEFAULT_USER=$USER
# POMPT='myPrompt'

################ plugins
# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

plugins=(git cargo sbt docker)

# if [ $commands[kubectl] ]; then
# function rprompt() {
#   kubectl config current-context
# }
# fi

## color chart: https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg
# RPROMPT='$FG[246] $(rprompt)%{$reset_color%'


source $ZSH/oh-my-zsh.sh

# Include Common
if [ -f ~/.commonrc ]; then
  . ~/.commonrc
fi

################ user config
# AWS CLI
if [ $commands[aws] ]; then
fi


