# Include Common
if [ -f ~/.commonrc ]; then
  . ~/.commonrc
fi

#if [ -f $HOME/.dotfiles/bash/sensible.bash ]; then
#   source $HOME/.dotfiles/bash/sensible.bash
#fi

#export PS1="\w "


bind TAB:menu-complete



### Aliases
alias tm="tmux"
### General
alias l="ls -al"
alias cc="clear"
alias xx="exit"
alias ..="cd ..;pwd;ls -a"
alias pp="pwd"
### Application Aliases
alias vi="vim"
### GIT Aliases
alias gs="git status"
alias gcm="git commit -m"
alias gca="git commit -am"
alias gco="git checkout"
alias gb="git branch"
alias gbd="git branch -D "
alias gbn="git checkout -b "
alias ga="git add"
alias gl="git log --color"
alias gitlg="git log -p --color"
alias gitl="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%C(bold blue)<%an>%Creset' --abbrev-commit"
alias gd="git diff --color"
alias gp="git pull; git fetch --all --prune"
alias gpp="git push origin HEAD; git push origin --tags"


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

#----------
# ENV
#----------
# Rust
if [ -x "$(command -v rustc)" ]; then
  export PATH="$HOME/.cargo/bin:$PATH"
  source $HOME/.cargo/env
  export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
fi
#export CARGO_INCREMENTAL=1

# Kube
if [ -x "$(command -v kubectl)" ]; then
  source <(kubectl completion bash)
fi
if [ -x "$(command -v helm)" ]; then
  source <(helm completion bash)
fi

# Go
if [ -x "$(command -v go)" ]; then
  export GOPATH=~/project/go
  export PATH=$PATH:$(go env GOPATH)/bin
fi

# Servo
export PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig

export PATH="/usr/local/sbin:$PATH"


#bash-completion
if [ -x "$(command -v brew)" ]; then
  [[ -f "$(brew --prefix)/etc/bash_completion" ]] && source "$(brew --prefix)/etc/bash_completion"
fi

#git-prompt
GIT_PROMPT_ONLY_IN_REPO=0
GIT_PROMPT_FETCH_REMOTE_STATUS=0   # uncomment to avoid fetching remote status
GIT_PROMPT_SHOW_UNTRACKED_FILES=no # can be no, normal or all; determines counting of untracked files
GIT_PROMPT_SHOW_CHANGED_FILES_COUNT=0 # uncomment to avoid printing the number of changed files
# GIT_PROMPT_THEME_FILE=~/.git-prompt-colors.sh
#source $HOME/.dotfiles/bash/bash-git-prompt/gitprompt.sh

#---------- from bash profile ...
export PATH=$PATH:~/bin



export POSTGRES="/Applications/Postgres.app/Contents/Versions/latest/bin"
export PATH=$POSTGRES:$PATH


export ANDROID_HOME="/Users/toidiu/android/android-sdk"
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH

export GAE_HOME="/Users/toidiu/android/appengine/appengine-java-sdk-1.9.23"
export PATH=$GAE_HOME/bin:$PATH

GRADLE_HOME=/Users/toidiu/android/gradle-binary/gradle2.5
export GRADLE_HOME
export PATH=$PATH:$GRADLE_HOME/bin



export PATH="/usr/local/opt/ruby/bin:$PATH"



[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH="/usr/local/sbin:$PATH"
