# Include Common
if [ -f ~/.commonrc ]; then
  . ~/.commonrc
fi

#if [ -f $HOME/.dotfiles/bash/sensible.bash ]; then
#   source $HOME/.dotfiles/bash/sensible.bash
#fi

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

#----------
# ENV
#----------
# Rust
if [ -x "$(command -v rustc)" ]; then
  export PATH="$HOME/.cargo/bin:$PATH"
  source $HOME/.cargo/env
  export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
fi

#bash-completion
if [ -x "$(command -v brew)" ]; then
  [[ -f "$(brew --prefix)/etc/bash_completion" ]] && source "$(brew --prefix)/etc/bash_completion"
fi

#git-prompt
GIT_PROMPT_ONLY_IN_REPO=0
GIT_PROMPT_FETCH_REMOTE_STATUS=0   # uncomment to avoid fetching remote status
GIT_PROMPT_SHOW_UNTRACKED_FILES=no # can be no, normal or all; determines counting of untracked files
GIT_PROMPT_SHOW_CHANGED_FILES_COUNT=0 # uncomment to avoid printing the number of changed files
# GIT_PROMPT_THEME_FILE=~/.git-prompt-colors.sh
#source $HOME/.dotfiles/bash/bash-git-prompt/gitprompt.sh

#---------- from bash profile ...
export PATH=$PATH:~/bin



export POSTGRES="/Applications/Postgres.app/Contents/Versions/latest/bin"
export PATH=$POSTGRES:$PATH


export ANDROID_HOME="/Users/toidiu/android/android-sdk"
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH

export GAE_HOME="/Users/toidiu/android/appengine/appengine-java-sdk-1.9.23"
export PATH=$GAE_HOME/bin:$PATH

GRADLE_HOME=/Users/toidiu/android/gradle-binary/gradle2.5
export GRADLE_HOME
export PATH=$PATH:$GRADLE_HOME/bin



export PATH="/usr/local/opt/ruby/bin:$PATH"


